@api = http://localhost:4000

### Register user
POST {{api}}/signup
Content-Type: application/json

{
	"email": "pepito123@gmail.com",
	"password": "dev12345@"
}

### View page welcome
GET {{api}}

### Register student
POST {{api}}/student
Content-Type: application/json
Authorization: Bearer rRwTdRQOsRXsf89KqWTfqJxik6q2

{
   "apellidos": "Developer",
   "nombres": "Challenge",
   "fechaNacimiento": "1992-05-16",
   "ciudad": "Ecuador",
   "correo": "dev456@gmail.com"
}

### Register schedule
POST {{api}}/schedule
Content-Type: application/json

{
	"idStd": "725de9af-c307-4df6-9eed-8582f4e2cda3",
	"courses": [
      {
         "desiredCourse": "PortfolioConstruction",
         "requiredCourse": "PortfolioTheories"
      }, {
         "desiredCourse": "InvestmentManagement",
         "requiredCourse": "Investment"
      }, {
         "desiredCourse": "Investment",
         "requiredCourse": "Finance"
      }, {
         "desiredCourse": "PortfolioTheories",
         "requiredCourse": "Investment"
      }, {
         "desiredCourse": "InvestmentStyle",
         "requiredCourse": "InvestmentManagement"
      }, {
         "desiredCourse": "Finance",
         "requiredCourse": "Programming"
      }
   ]
}

### Search schedule for students
GET {{api}}/searchSchedule/725de9af-c307-4df6-9eed-8582f4e2cda3
Content-Type: application/json
